openapi: 3.0.3
info:
  title: Authorization service 
  description: |-
    Scala backend homework, Mukhametgalin Artur
  version: "1.0"
externalDocs:
  url: https://edu.tinkoff.ru/my-activities/courses/stream/80378e3d-aa9d-47c1-8af1-d6115e989712/exam/8107/1
  description: problem statement
servers:
  - url: https://example.com


paths:
  /auth/register:
    post:
      tags:
        - authorization
      summary: user's registration
      description: Create user by username and password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAuthData'
        required: true
      responses:
        '201':
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
                
        '400': 
          description: Username or password is not valid
          content:
            application/json:
              schema:
                $ref: "definitions.yaml#/components/schemas/AuthError"

        '409':
          description: Username is taken
          content:
            application/json:
              schema:
                $ref: "definitions.yaml#/components/schemas/AuthError"

        '500':
          description: Internal server error

  /auth/login:
    post:
      tags:
          - authorization
      summary: user authentication
      description: Log in by username and password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAuthData'
        required: true
      responses:
        '200':
          description: Successful authorization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'

        '400': 
          description: The password is not correct
          content:
            application/json:
              schema:
                $ref: "definitions.yaml#/components/schemas/AuthError"

        '409':
          description: User does not exist
          content:
            application/json:
              schema:
                $ref: "definitions.yaml#/components/schemas/AuthError"

        '500':
          description: Internal server error


components:

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserAuthData:
      required:
        - username
        - password
      type: object
      description: user's data for authorization
      properties:
        username:
          type: string
          example: i_am_user_1
        password:
          type: string
          example: password1
        repeatedPassword:
          type: string
          example: password2

    AuthToken:
      type: string
      example: i_am_token
