version: "3.9"

services:
  auth-database:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
    ports:
      - "${AUTH_POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    env_file:
      - .env
    environment:
      - AUTH_POSTGRES_HOST=auth-database
      - AUTH_POSTGRES_PORT=5432
    ports:
      - "${AUTH_HTTP_PORT}:${AUTH_HTTP_PORT}"
    depends_on:
      auth-database:
        condition: service_healthy

  routing-database:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${ROUTING_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ROUTING_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ROUTING_POSTGRES_DB}
    ports:
      - "${ROUTING_POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  routing-balancer:
    image: nginx
    env_file:
      - .env
    ports:
      - "${ROUTING_BALANCER_HTTP_PORT}:${ROUTING_BALANCER_HTTP_PORT}"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./routing/src/main/resources/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template"
    command: /bin/bash -c "envsubst < etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - routing-service1
      - routing-service2
      - routing-service3

  routing-service1:
    build:
      context: .
      dockerfile: ./routing/Dockerfile
    env_file:
      - .env
    environment:
      - ROUTING_HTTP_PORT=${ROUTING1_HTTP_PORT}
      - ROUTING_POSTGRES_HOST=routing-database
      - ROUTING_POSTGRES_PORT=5432
    ports:
      - "${ROUTING1_HTTP_PORT}:${ROUTING1_HTTP_PORT}"
    depends_on:
      routing-database:
        condition: service_healthy

  routing-service2:
    build:
      context: .
      dockerfile: ./routing/Dockerfile
    env_file:
      - .env
    environment:
      - ROUTING_HTTP_PORT=${ROUTING2_HTTP_PORT}
      - ROUTING_POSTGRES_HOST=routing-database
      - ROUTING_POSTGRES_PORT=5432
    ports:
      - "${ROUTING2_HTTP_PORT}:${ROUTING2_HTTP_PORT}"
    depends_on:
      routing-database:
        condition: service_healthy

  routing-service3:
    build:
      context: .
      dockerfile: ./routing/Dockerfile
    env_file:
      - .env
    environment:
      - ROUTING_HTTP_PORT=${ROUTING3_HTTP_PORT}
      - ROUTING_POSTGRES_HOST=routing-database
      - ROUTING_POSTGRES_PORT=5432
    ports:
      - "${ROUTING3_HTTP_PORT}:${ROUTING3_HTTP_PORT}"
    depends_on:
      routing-database:
        condition: service_healthy

  image-service:
    build:
      context: .
      dockerfile: ./image/Dockerfile
    env_file:
      - .env
    ports:
      - "${IMAGE_HTTP_PORT}:${IMAGE_HTTP_PORT}"
