version: "3.9"

services:
  auth:
    build: .
    ports:
      - "8082:8082"
    expose:
      - "8082"
    entrypoint: ["java", "-jar", "/opt/routing-service/auth.jar"]
  routing:
    build: .
    ports:
      - "8081:8081"
    expose:
      - "8081"
    entrypoint: ["java", "-jar", "/opt/routing-service/routing.jar"]
