version: "3.9"

services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    ports:
      - "8082:8082"
    expose:
      - "8082"
  routing:
    build:
      context: .
      dockerfile: routing/Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
