version: "3.9"

services:
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "7777:5432"
    volumes:
      - database-data:/var/lib/postgresqldata
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    ports:
      - "8082:8082"
    expose:
      - "8082"
  routing:
    build:
      context: .
      dockerfile: routing/Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"

volumes:
  database-data: