openapi: 3.0.3
info:
  title: Route search service
  description: |-
    Scala backend homework, Mukhametgalin Artur
  version: "1.0"
externalDocs:
  url: https://edu.tinkoff.ru/my-activities/courses/stream/80378e3d-aa9d-47c1-8af1-d6115e989712/exam/8107/1
  description: problem statement
servers:
  - url: https://example.com

paths:
  /route:
    post:
      tags:
        - Routing
      summary: Find a route
      description: Give the user a route through a set of point's ids
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Points'
        required: true
      responses:
        '200':
          description: Route is found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Route'
        '400':
          description: Request points is not correct
          content:
            application/json:
              schema:
                $ref: 'definitions.yaml#/components/schemas/RoutingError'
        '401': 
          description: Unauthorized
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PointId:
      type: string
      example: id_12345
    
    Point:
      required:
        - id
      type: object
      description: Point 
      properties:
        id:
          $ref: '#/components/schemas/PointId'
        payload:
          type: string
          description: Additional information of point
          example: Some info about point
    
    Points:
      required:
        - ids
      type: object
      description: Array of point's ids
      properties:
        ids:
          type: array
          items:
            $ref: '#/components/schemas/PointId'

    Route:
      required:
        - points
      type: object
      description: Route as a sequence of points
      properties:
        points: 
          type: array
          items:
            $ref: '#/components/schemas/Point'
