openapi: 3.0.3

info:
  title: Route search services
  description: Title
  version: 0.1.0

paths:
  /auth/register:
    post:
      summary: User registration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                email:
                  type: string
                  example: example@cornhub.com
                password:
                  type: string
                  example: Password1234
              required:
                - username
                - password
      responses:
        '201':
          description: User created.
        '400':
          description: Bad request.
        '409':
          description: Already exists.
        '415':
          description: Unsupported Media Type.

  /auth/login:
    get:
      summary: User login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: example@cornhub.com
                password:
                  type: string
                  example: Password1234
              required:
                - username
                - password
      responses:
        '201':
          description: Valid Login.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
        '400':
          description: Bad request.
        '415':
          description: Unsupported Media Type.

  /routing:
    post:
      summary: Finding route
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                route_points_list:
                  type: string
                  example: "[point1, point2, point3]"
              required:
                - route_points_list
      responses:
        '201':
          description: Valid Login.
          content:
            application/json:
              schema:
                type: object
                properties:
                  paved_route_points_list:
                    type: string
                    example: "[point1, point2, point3]"
                required:
                  - paved_route_points_list
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '415':
          description: Unsupported Media Type.
