version: "3.9"

services:
  database:
    image: postgres
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  auth:
    build:
      context: ..
      dockerfile: ./auth/Dockerfile
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - database

  routing:
    build:
      context: ..
      dockerfile: ./routing/Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"

  image:
    build:
      context: ..
      dockerfile: ./image/Dockerfile
    ports:
      - "8090:8090"
    expose:
      - "8090"

volumes:
  database-data:
