openapi: 3.0.3
info:
  title: Image Service
  description: Image Service
  version: 1.0.0

servers:
  - url: http://localhost:8090

paths:
  /upload/{node_id}:
    put:
      summary: You can add one photo in jpeg format up to 10 MB to a house or intersection.

      requestBody:
        required: true
        content:
          image/jpeg:
            schema:
              type: string
              format: binary

      security:
        - bearerAuth: [ ]

      responses:
        "200":
          description: Image uploaded successfully

        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "../definitions.yaml#/components/schemas/Error"

        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "../definitions.yaml#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
