openapi: 3.0.0
info:
    description: photo upload service
    title: photo upload service
    version: 1.0.0

servers:
    - url: http://localhost:8000

paths:
    /upload:
        put:
            description: Upload image
            requestBody:
                required: true
                content:
                    image/jpeg:
                        schema:
                            type: string
                            format: binary
            parameters:
              - name: nodeId
                in: query
                required: true
                schema:
                    type: integer

            responses:
                "200":
                    description: Successfully uploaded
                "400":
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: "../definitions.yaml#/components/schemas/Error"
                "422":
                    description: file is too big
                    content:
                        application/json:
                            schema:
                                $ref: "../definitions.yaml#/components/schemas/Error"

    /download:
        get:
            description: get image by node id
            parameters:
              - name: nodeId
                in: query
                required: true
                schema:
                    type: integer

            responses:
                "200":
                    description: Image by node id
                    content:
                        image/jpeg:
                            schema:
                              type: string
                              format: binary
                "400":
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: "../definitions.yaml#/components/schemas/Error"
