openapi: 3.0.3

info:
  title: Route search service
  description: API for searching route
  version: 0.1.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RoutePoints:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
        required:
          - id
          - name

paths:
  /routing:
    post:
      summary: Route search
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoutePoints'
      responses:
        '200':
          description: Route found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutePoints'
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
