on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: restore deps for lint step
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Format code
        run: sbt scalafmtSbtCheck scalafmtCheckAll
      - name: cache deps for lint step
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: restore deps for test step
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run local tests
        run: sbt -v test
      - name: cache deps for test step
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
